# Use a simple incremented version number.
version: '{build}'

# Download the repository as a zip archive.
# https://www.appveyor.com/docs/how-to/repository-shallow-clone/
shallow_clone: true

environment:
  matrix:

    - CHANNEL: stable
      ARCH: i686

    - CHANNEL: stable
      ARCH: x86_64

    - CHANNEL: nightly
      ARCH: i686

    - CHANNEL: nightly
      ARCH: x86_64

install:
  # Install Rust
  - appveyor-retry appveyor downloadfile https://win.rustup.rs/ -filename rustup-init.exe -timeout 60000
  - rustup-init --version
  - rustup-init -y --default-toolchain %CHANNEL%-%ARCH%-pc-windows-gnu
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc --version
  - cargo --version

  - ps: .appveyor\setup-gnu.ps1

# We do everything in the test_script phase, so we disable the build phase to
# avoid AppVeyor trying to build something and failing.
build: false

test_script:
  - copy config %USERPROFILE%\.cargo\config
  - type %USERPROFILE%\.cargo\config
  - cargo build -vv
  - del %USERPROFILE%\.cargo\config
  - cargo clean
  - cargo build -vv
